#Additional Policy EC2

#CreateNetworkInterface EC2
#DescribeNetworkInterfaces EC2
#Delete DescribeNetworkInterfaces EC2

Resources:
  lambdaFunction: 
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: 
        S3Bucket: lambda-code-cloudformation
        S3Key: app.zip
      FunctionName: FunctionJefferson
      Description: Teste-Jefferson Description
      Runtime: nodejs8.10
      MemorySize: 128
      Handler: handler
      Role: arn:aws:iam::675796402854:role/ExecuteSQSAndSNSFromLambda
      Environment: 
        Variables:
           "PORT": "3000"
      Timeout: 10
      VpcConfig:
        SecurityGroupIds:
          - sg-0e585177b46f4a7e0
        SubnetIds:
          - subnet-0c8df0c9d5f908b64

  sqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      QueueName: FunctionJeffersonQueue
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 10
  
  sqsTrigger:   
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: false
      EventSourceArn: !GetAtt sqsQueue.Arn
      FunctionName: !GetAtt lambdaFunction.Arn

